<a href="https://colab.research.google.com/github/JulieYego/AI-assignment/blob/main/AI%20ML%20Group%20Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd #dataset library
import numpy as np #linear algebra library

In [44]:
from numpy import array #library for the matrices
from sklearn.preprocessing import Normalizer #ML library
from keras.activations import sigmoid #library for sigmoid function
from keras.losses import mse #library for mean squared error
from numpy.random import uniform,normal #library for generating random numbers

Hyperparameters

In [45]:
batch_size = 2
learning_param = 0.07

Data Transformation

In [46]:
data_dict = {'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [47]:
data = pd.DataFrame(data_dict)

In [48]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [49]:
x = data.drop('Target',axis=1)
y = data['Target']

In [50]:
x_trans = Normalizer(norm='max').fit_transform(x)

In [51]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [52]:
y = Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [53]:
y

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [54]:
x_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [55]:
Normalizer().fit_transform(data) #transform the dataset

array([[0.40824829, 0.54433105, 0.68041382, 0.27216553],
       [0.58191437, 0.72739297, 0.29095719, 0.21821789],
       [0.60971076, 0.2438843 , 0.18291323, 0.73165291],
       [0.20936957, 0.15702718, 0.62810871, 0.73279349],
       [0.14157875, 0.56631501, 0.66070085, 0.47192918],
       [0.53452248, 0.62360956, 0.4454354 , 0.35634832]])

ANN Model from Scratch

In [56]:
'''weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])'''

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [57]:
weight_1 = uniform(-1,1,(3,2)) #shape of 3 by 2
weight_2 = uniform(-1,1,(2,1)) #shape of 2 by 1

In [58]:
weight_2

array([[ 0.98100663],
       [-0.29412575]])

In [59]:
x=x_trans

In [60]:
batch_1 = x[0:batch_size]

In [61]:
batch_1

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [62]:
batch_2 = x[batch_size:4]

In [63]:
batch_2

array([[1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ]])

In [64]:
batch_3 = x[4:6]

In [65]:
batch_3

array([[0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [66]:
#output_1 = x[0]@weight_1
#output_1

Sumation of the product of inputs and their weights for each batch

Batch 1

In [67]:
output_1 = batch_1@weight_1
output_1

array([[ 1.1304151 , -0.25715703],
       [ 0.60974599,  0.31261287]])

Batch 2

In [68]:
output_2 = batch_2@weight_1
output_2

array([[ 0.95236404,  0.47389996],
       [ 1.15890198, -0.47051874]])

Batch 3

In [69]:
output_3 = batch_3@weight_1
output_3

array([[ 0.78135753, -0.50727774],
       [ 0.97006894,  0.12798271]])

Activation Function

Batch 1

In [70]:
act_output_1 = sigmoid(output_1).numpy()
act_output_1

array([[0.7559155 , 0.4360627 ],
       [0.64788286, 0.57752291]])

Batch 2

In [71]:
act_output_2 = sigmoid(output_2).numpy()
act_output_2

array([[0.72159036, 0.61630641],
       [0.76113314, 0.38449347]])

Batch 3

In [72]:
act_output_3 = sigmoid(output_3).numpy()
act_output_3

array([[0.68597262, 0.3758319 ],
       [0.72513324, 0.53195207]])

Outputs multiplied by the hidden matrix and the predicted outcome and true outcome

Batch 1

In [73]:
final_output_1 = act_output_1@weight_2
final_output_1

array([[0.61330085],
       [0.46571302]])

In [74]:
y_true_1 = y[0][0:batch_size]
y_pred_1 = final_output_1.T[0]

In [75]:
y_true_1

array([0.28571429, 0.21428571])

In [76]:
y_pred_1.T

array([0.61330085, 0.46571302])

Batch 2

In [77]:
final_output_2 = act_output_2@weight_2
final_output_2

array([[0.52661334],
       [0.63358723]])

In [78]:
y_true_2 = y[0][batch_size:4]
y_pred_2 = final_output_2.T[0]

In [79]:
y_true_2

array([0.85714286, 1.        ])

In [80]:
y_pred_2

array([0.52661334, 0.63358723])

Batch 3

In [81]:
final_output_3 = act_output_3@weight_2
final_output_3

array([[0.56240185],
       [0.55489972]])

In [82]:
y_true_3 = y[0][4:6]
y_pred_3 = final_output_3.T[0]

In [83]:
y_true_3

array([0.71428571, 0.57142857])

In [84]:
y_pred_3

array([0.56240185, 0.55489972])

Computing Mean Squared Error

In [85]:
mse(y_true_1,y_pred_1).numpy() #MSE error for batch 1

0.0852643241734814

In [86]:
mse(y_true_2,y_pred_2).numpy() #MSE error for batch 2

0.1217540384423312

In [87]:
mse(y_true_3,y_pred_3).numpy() #MSE error for batch 3

0.011670955724633633

Updating the weights using delta rules of error computation

In [88]:
#calculate the first order derivative of the sigmoid function 
def sigmoid(s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))

In [114]:
def back(y, y_hat):
        #error through the network
        #y is the expected outcome(y_true)
        output_error = y - y_hat # error in output
        output_delta = output_error * sigmoid(y_hat, deriv=True)
        return output_delta 

In [120]:
def calculateGradient(W, y, y_hat, learningRate):
    #y is the expected outcome(y_true)
    #y_hat is the predicted outcome(y_pred)
  
    output_delta = (y - y_hat) * sigmoid(y_hat, deriv=True) #error 
    output_delta = np.sum(output_delta, axis=0)

    temp = np.array(learningRate * output_delta)
    W = W + temp
    return W

In [119]:
calculateGradient(weight_1,y_true_1,y_pred_1,learning_param) #updated weights

array([[ 0.82734059,  0.64880602],
       [-0.46750693,  0.05877998],
       [ 0.98445385, -0.71702707]])

In [124]:
for i in range(100): #trains the ANN 100 times
    upd_weight_1 = calculateGradient(weight_1,y_true_1,y_pred_1,learning_param)
    upd_weight_2 = calculateGradient(weight_2,y_true_1,y_pred_1,learning_param)

In [93]:
print("Actual output: " + str(y))

Actual output: [[0.28571429 0.21428571 0.85714286 1.         0.71428571 0.57142857]]


In [102]:
print("Weights for first layer: \n" + str(weight_1))

Weights for first layer: 
[[ 0.83715827  0.65862371]
 [-0.45768924  0.06859766]
 [ 0.99427154 -0.70720939]]


In [103]:
print("Weights for second layer: \n" + str(weight_2))

Weights for second layer: 
[[ 0.98100663]
 [-0.29412575]]


In [125]:
print("Updated weights for first layer: \n" + str(upd_weight_1))

Updated weights for first layer: 
[[ 0.82734059  0.64880602]
 [-0.46750693  0.05877998]
 [ 0.98445385 -0.71702707]]


In [126]:
print("Updated weights for second layer: \n" + str(upd_weight_2))

Updated weights for second layer: 
[[ 0.97118895]
 [-0.30394343]]
