<a href="https://colab.research.google.com/github/JulieYego/AI-assignment/blob/main/AI_ANN_updated1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [145]:
import pandas as pd #dataset library
import numpy as np #linear algebra library

In [146]:
from numpy import array #library for the matrices
from sklearn.preprocessing import Normalizer #ML library
from keras.activations import sigmoid #library for sigmoid function
from keras.losses import mse #library for mean squared error
from numpy.random import uniform,normal #library for generating random numbers

Hyperparameters

In [147]:
batch_size = 2
learning_param = 0.07

Data Transformation

In [148]:
data_dict = {'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [149]:
data = pd.DataFrame(data_dict)

In [150]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [151]:
x = data.drop('Target',axis=1)
y = data['Target']

In [152]:
x_trans = Normalizer(norm='max').fit_transform(x)

In [153]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [154]:
y = Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [155]:
y

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [156]:
x_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [157]:
Normalizer().fit_transform(data) #transform the dataset

array([[0.40824829, 0.54433105, 0.68041382, 0.27216553],
       [0.58191437, 0.72739297, 0.29095719, 0.21821789],
       [0.60971076, 0.2438843 , 0.18291323, 0.73165291],
       [0.20936957, 0.15702718, 0.62810871, 0.73279349],
       [0.14157875, 0.56631501, 0.66070085, 0.47192918],
       [0.53452248, 0.62360956, 0.4454354 , 0.35634832]])

ANN Model from Scratch

In [158]:
'''weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])'''

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [159]:
weight_1 = uniform(-1,1,(3,2)) #shape of 3 by 2
weight_2 = uniform(-1,1,(2,1)) #shape of 2 by 1

In [160]:
weight_2

array([[0.40768405],
       [0.38340239]])

In [203]:
weight_2[0][0]

0.4076840511051556

In [204]:
weight_2[1][0]

0.383402386122782

In [161]:
x=x_trans

In [162]:
x[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [163]:
output_1 = x[0:batch_size]@weight_1
output_1

array([[-0.11175532, -0.42733078],
       [ 0.00336933, -0.05275888]])

Activation Function

In [164]:
act_output_1 = sigmoid(output_1).numpy()
act_output_1

array([[0.47209021, 0.3947639 ],
       [0.50084233, 0.48681334]])

In [165]:
final_output_1 = act_output_1@weight_2
final_output_1

array([[0.34381707],
       [0.39083083]])

In [181]:
y_true = y[0][0:batch_size]
y_pred = final_output_1.T[0]

In [182]:
y_true

array([0.28571429, 0.21428571])

In [183]:
y_pred.T

array([0.34381707, 0.39083083])

Computing Mean Squared Error

In [185]:
mse(y_true,y_pred).numpy() #MSE error

0.01727205518361269

Updating the weights using delta rules of error computation

In [176]:
#calculate the first order derivative of the sigmoid function 
def first_der(s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))

In [369]:
weight_2[0]

array([0.40768405])

In [370]:
for i in range(100):
   error_k = (y_true - y_pred) * first_der(y_pred, deriv=True) #error at node k
   error_j = error_k * weight_2[0] * first_der(act_output_1[0], deriv=True) #error at node j
   error_i = error_k * weight_2[1] * first_der(act_output_1[1], deriv=True) #error at node i

   delta_weight_k = np.array(learning_param * error_k * y_pred)
   delta_weight_k
     

In [378]:
delta_weight_k = np.array(learning_param * error_k * y_pred)
delta_weight_k

upd = weight_2[0][0] + delta_weight_k
upd



array([0.40736857, 0.40653413])

In [381]:
delta_weight_j = (learning_param * error_j * act_output_1[0][0])
delta_weight_j

array([-4.40129801e-05, -1.35298020e-04])

In [357]:
print("Updated weight_2 : " + str(upd_weight_2))

for i in range(len(weight_2)):
      upd_weight_2 = weight_2[i][0] + delta_weight_k
      #print(upd_weight_2) 
delta_weight_j = (learning_param * error_j * act_output_1[0][0])
   delta_weight_j = np.array(learning_param * error_j * act_output_1[0][0])
   for i in range(len(weight_1)):
      upd_weight_1j = weight_1[i][0] + delta_weight_j
      #print(upd_weight_1j)

   delta_weight_i = np.array(learning_param * error_i * act_output_1[1][0])
   for i in range(len(weight_1)-1):
      upd_weight_1i = weight_1[0][i] + delta_weight_i
    #print(upd_weight_1i)


Updated weight_2 : [0.3830869  0.38225246]


In [355]:
print("Updated weight_1 : " + str(upd_weight_1j))

Updated weight_1 : [-0.1918649  -0.19195618]


In [356]:
print("Updated weight_1 : " + str(upd_weight_1i))

Updated weight_1 : [-0.32590791 -0.32600501]
