<a href="https://colab.research.google.com/github/JulieYego/AI-assignment/blob/main/AI_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd #dataset library
import numpy as np #linear algebra library

In [78]:
from numpy import array #library for the matrices
from sklearn.preprocessing import Normalizer #ML library
from keras.activations import sigmoid #library for sigmoid function
from keras.losses import mse #library for mean squared error
from numpy.random import uniform,normal

Hyperparameters

In [79]:
batch_size = 2

Data Transformation

In [80]:
data_dict = {'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [81]:
data = pd.DataFrame(data_dict)

In [82]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [83]:
x = data.drop('Target',axis=1)
y = data['Target']

In [84]:
x_trans = Normalizer(norm='max').fit_transform(x)

In [85]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [86]:
y = Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [87]:
y

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [88]:
x_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [89]:
Normalizer().fit_transform(data) #transform the dataset

array([[0.40824829, 0.54433105, 0.68041382, 0.27216553],
       [0.58191437, 0.72739297, 0.29095719, 0.21821789],
       [0.60971076, 0.2438843 , 0.18291323, 0.73165291],
       [0.20936957, 0.15702718, 0.62810871, 0.73279349],
       [0.14157875, 0.56631501, 0.66070085, 0.47192918],
       [0.53452248, 0.62360956, 0.4454354 , 0.35634832]])

ANN Model from Scratch

In [90]:
'''weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])'''

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [91]:
weight_1 = uniform(-1,1,(3,2)) #shape of 3 by 2
weight_2 = uniform(-1,1,(2,1)) #shape of 2 by 1

In [92]:
x=x_trans

In [93]:
x[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [94]:
#output_1 = x[0]@weight_1
#output_1

In [95]:
output_1 = x[0:batch_size]@weight_1
output_1

array([[ 1.70987501,  0.01442567],
       [ 1.62478758, -0.31628351]])

In [96]:
act_output_1 = sigmoid(output_1).numpy()
act_output_1

array([[0.84682007, 0.50360636],
       [0.83545434, 0.42158175]])

In [97]:
final_output = act_output_1@weight_2
final_output

array([[-0.0590683 ],
       [-0.05912835]])

In [98]:
y_true = y[0][0:batch_size]
y_pred = final_output.T[0]

In [99]:
y_true

array([0.28571429, 0.21428571])

In [103]:
y_pred.T

array([-0.0590683 , -0.05912835])

Computing Mean Squared Error

In [101]:
mse(y_true,y_pred).numpy()

0.09681514092343765