<a href="https://colab.research.google.com/github/JulieYego/AI-assignment/blob/main/AI_ANN_updated.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import pandas as pd #dataset library
import numpy as np #linear algebra library

In [27]:
from numpy import array #library for the matrices
from sklearn.preprocessing import Normalizer #ML library
from keras.activations import sigmoid #library for sigmoid function
from keras.losses import mse #library for mean squared error
from numpy.random import uniform,normal

Hyperparameters

In [166]:
batch_size = 2
learning_param = 0.07

Data Transformation

In [29]:
data_dict = {'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
           'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [30]:
data = pd.DataFrame(data_dict)

In [31]:
data

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [32]:
x = data.drop('Target',axis=1)
y = data['Target']

In [33]:
x_trans = Normalizer(norm='max').fit_transform(x)

In [34]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [35]:
y = Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [36]:
y

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

In [37]:
x_trans

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [38]:
Normalizer().fit_transform(data) #transform the dataset

array([[0.40824829, 0.54433105, 0.68041382, 0.27216553],
       [0.58191437, 0.72739297, 0.29095719, 0.21821789],
       [0.60971076, 0.2438843 , 0.18291323, 0.73165291],
       [0.20936957, 0.15702718, 0.62810871, 0.73279349],
       [0.14157875, 0.56631501, 0.66070085, 0.47192918],
       [0.53452248, 0.62360956, 0.4454354 , 0.35634832]])

ANN Model from Scratch

In [39]:
'''weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])'''

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [40]:
weight_1 = uniform(-1,1,(3,2)) #shape of 3 by 2
weight_2 = uniform(-1,1,(2,1)) #shape of 2 by 1

In [160]:
weight_2

array([[-0.23439148],
       [ 0.15455852]])

In [41]:
x=x_trans

In [53]:
batch_1 = x[0:batch_size]

In [109]:
batch_1

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [55]:
batch_2 = x[batch_size:4]

In [56]:
batch_2

array([[1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ]])

In [57]:
batch_3 = x[4:6]

In [58]:
batch_3

array([[0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [118]:
#output_1 = x[0]@weight_1
#output_1

Sumation of the product of inputs and their weights for each batch

Batch 1

In [59]:
output_1 = batch_1@weight_1
output_1

array([[0.89908346, 0.60945003],
       [0.92699337, 0.16647356]])

Batch 2

In [60]:
output_2 = batch_2@weight_1
output_2

array([[ 0.42505122, -0.0949539 ],
       [ 0.44609769,  0.60171543]])

Batch 3

In [61]:
output_3 = batch_3@weight_1
output_3

array([[0.9330339 , 0.7661937 ],
       [1.00218116, 0.35807152]])

Activation Function

Batch 1

In [45]:
act_output_1 = sigmoid(output_1).numpy()
act_output_1

array([[0.71076112, 0.64781534],
       [0.71646491, 0.54152254]])

Batch 2

In [62]:
act_output_2 = sigmoid(output_2).numpy()
act_output_2

array([[0.60469133, 0.47627934],
       [0.60971103, 0.64604867]])

Batch 3

In [63]:
act_output_3 = sigmoid(output_3).numpy()
act_output_3

array([[0.71769039, 0.68269694],
       [0.73148721, 0.58857352]])

Outputs multiplied by the hidden matrix and the predicted outcome and true outcome

Batch 1

In [64]:
final_output_1 = act_output_1@weight_2
final_output_1

array([[-0.06647097],
       [-0.08423635]])

In [75]:
y_true_1 = y[0][0:batch_size]
y_pred_1 = final_output.T[0]

In [76]:
y_true_1

array([0.28571429, 0.21428571])

In [77]:
y_pred_1.T

array([-0.06647097, -0.08423635])

Batch 2

In [65]:
final_output_2 = act_output_2@weight_2
final_output_2

array([[-0.06812147],
       [-0.04305875]])

In [78]:
y_true_2 = y[0][batch_size:4]
y_pred_2 = final_output_2.T[0]

In [79]:
y_true_2

array([0.85714286, 1.        ])

In [80]:
y_pred_2

array([-0.06812147, -0.04305875])

Batch 3

In [66]:
final_output_3 = act_output_3@weight_2
final_output_3

array([[-0.06270389],
       [-0.08048532]])

In [81]:
y_true_3 = y[0][4:6]
y_pred_3 = final_output_3.T[0]

In [82]:
y_true_3

array([0.71428571, 0.57142857])

In [83]:
y_pred_3

array([-0.06270389, -0.08048532])

Computing Mean Squared Error

In [84]:
mse(y_true_1,y_pred_1).numpy() #error for batch 1

0.10657494024377544

In [85]:
mse(y_true_2,y_pred_2).numpy() #error for batch 2

0.9720428094683073

In [86]:
mse(y_true_3,y_pred_3).numpy() #error for batch 3

0.5143522817636723

Updating the weights using delta rules of error computation

In [112]:
#calculate the first order derivative of the sigmoid function 
def sigmoid(s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))

In [149]:
def back(y, y_hat):
        #error through the network
        #z is the 
        #y is the expected outcome(y_true)
        output_error = y - y_hat # error in output
        output_delta = output_error * sigmoid(y_hat, deriv=True)
        return output_delta
        
       

In [164]:
def calculateGradient(W, y, y_hat, learningRate):
    #y is the expected outcome(y_true)
    #y_hat is the predicted outcome(y_pred)
  
    output_delta = (y - y_hat) * sigmoid(y_hat, deriv=True) #gradient
    output_delta = np.sum(output_delta, axis=0)
    temp = np.array(learningRate * output_delta)
    W = W + temp
    return output_delta,W

In [167]:
calculateGradient(weight_2,y_true_1,y_pred_1,learning_param)

(-0.05223084035642357, array([[-0.23804764],
        [ 0.15090236]]))

In [169]:
for i in range(100): #trains the ANN 100 times
    calculateGradient(weight_2,y_true_1,y_pred_1,learning_param)

In [171]:
print("Actual output: " + str(y))

Actual output: [[0.28571429 0.21428571 0.85714286 1.         0.71428571 0.57142857]]


In [ ]:
print("Predicted output: " + str(X))