<a href="https://colab.research.google.com/github/JulieYego/AI-assignment/blob/main/Feature_Extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import pandas as pd
from sklearn.decomposition import TruncatedSVD,PCA
from numpy.linalg import svd

In [14]:
t_svd = TruncatedSVD(3)
pca = PCA(3)

In [3]:
size= 100

In [20]:
values = np.random.uniform(10,100,size)

In [40]:
data = {'Loc': values, 'Size' : values, 'Ambience' : values, 'Mall_Near' : values,
        'Road_Near' : values, 'Monthly_Rent' : values} 

In [41]:
df = pd.DataFrame(data)
print(df)

          Loc       Size   Ambience  Mall_Near  Road_Near  Monthly_Rent
0   85.003024  85.003024  85.003024  85.003024  85.003024     85.003024
1   34.631362  34.631362  34.631362  34.631362  34.631362     34.631362
2   73.940796  73.940796  73.940796  73.940796  73.940796     73.940796
3   87.966448  87.966448  87.966448  87.966448  87.966448     87.966448
4   80.912937  80.912937  80.912937  80.912937  80.912937     80.912937
..        ...        ...        ...        ...        ...           ...
95  46.682493  46.682493  46.682493  46.682493  46.682493     46.682493
96  24.677522  24.677522  24.677522  24.677522  24.677522     24.677522
97  10.054882  10.054882  10.054882  10.054882  10.054882     10.054882
98  18.334589  18.334589  18.334589  18.334589  18.334589     18.334589
99  34.404235  34.404235  34.404235  34.404235  34.404235     34.404235

[100 rows x 6 columns]


In [45]:
#df_new = df.drop("Monthly_Rent", axis = 1, inplace=True)
print(df)

          Loc       Size   Ambience  Mall_Near  Road_Near
0   85.003024  85.003024  85.003024  85.003024  85.003024
1   34.631362  34.631362  34.631362  34.631362  34.631362
2   73.940796  73.940796  73.940796  73.940796  73.940796
3   87.966448  87.966448  87.966448  87.966448  87.966448
4   80.912937  80.912937  80.912937  80.912937  80.912937
..        ...        ...        ...        ...        ...
95  46.682493  46.682493  46.682493  46.682493  46.682493
96  24.677522  24.677522  24.677522  24.677522  24.677522
97  10.054882  10.054882  10.054882  10.054882  10.054882
98  18.334589  18.334589  18.334589  18.334589  18.334589
99  34.404235  34.404235  34.404235  34.404235  34.404235

[100 rows x 5 columns]


In [47]:
new_data = df.to_numpy()
new_data

array([[85.00302398, 85.00302398, 85.00302398, 85.00302398, 85.00302398],
       [34.63136219, 34.63136219, 34.63136219, 34.63136219, 34.63136219],
       [73.94079576, 73.94079576, 73.94079576, 73.94079576, 73.94079576],
       [87.96644806, 87.96644806, 87.96644806, 87.96644806, 87.96644806],
       [80.91293742, 80.91293742, 80.91293742, 80.91293742, 80.91293742],
       [18.44160921, 18.44160921, 18.44160921, 18.44160921, 18.44160921],
       [34.29242089, 34.29242089, 34.29242089, 34.29242089, 34.29242089],
       [83.02493353, 83.02493353, 83.02493353, 83.02493353, 83.02493353],
       [89.44798884, 89.44798884, 89.44798884, 89.44798884, 89.44798884],
       [77.60141019, 77.60141019, 77.60141019, 77.60141019, 77.60141019],
       [14.81236208, 14.81236208, 14.81236208, 14.81236208, 14.81236208],
       [38.99148815, 38.99148815, 38.99148815, 38.99148815, 38.99148815],
       [63.68372553, 63.68372553, 63.68372553, 63.68372553, 63.68372553],
       [61.93765946, 61.93765946, 61.9

In [48]:
pca.fit(new_data)

PCA(n_components=3)

In [49]:
trans_data = pca.transform(new_data)
trans_data

array([[ 7.07533474e+01,  4.31508803e-16, -1.73971919e-16],
       [-4.18811125e+01, -4.05301158e-16,  2.34627674e-17],
       [ 4.60174531e+01, -1.61737515e-15,  4.24552223e-16],
       [ 7.73797651e+01, -3.43307074e-15,  5.26496582e-16],
       [ 6.16076358e+01,  1.61970882e-16, -2.12012521e-15],
       [-7.80825007e+01,  1.35123722e-15,  9.71676619e-16],
       [-4.26390083e+01, -3.72414195e-16,  2.97013276e-16],
       [ 6.63302026e+01, -1.36893194e-15, -1.33274189e-15],
       [ 8.06925910e+01, -3.48490828e-15, -5.59395051e-16],
       [ 5.42028358e+01,  2.89370824e-16, -3.11824480e-15],
       [-8.61977440e+01, -4.44181998e-16,  2.99558345e-16],
       [-3.21315745e+01,  1.03970578e-15,  3.36005646e-16],
       [ 2.30819468e+01, -1.10995753e-15, -5.49513232e-16],
       [ 1.91776244e+01, -5.27684557e-16, -3.26141111e-16],
       [ 5.77792679e+01, -2.01206702e-15, -8.10841283e-16],
       [ 4.35325927e+01, -2.07736666e-15, -9.33116264e-16],
       [-8.06968259e+01, -3.19687951e-17

In [50]:
pca.explained_variance_ratio_

array([1.00000000e+00, 3.92768218e-34, 6.84426265e-65])

In [51]:
t_svd.fit_transform(df)

array([[ 1.90072540e+02, -9.18496531e-15,  3.87715441e-14],
       [ 7.74380800e+01, -5.42677779e-15,  1.49667871e-14],
       [ 1.65336646e+02, -1.02750738e-14,  2.88124655e-14],
       [ 1.96698958e+02, -1.04324288e-14,  3.43894445e-14],
       [ 1.80926828e+02, -1.02631170e-14,  3.48317546e-14],
       [ 4.12366918e+01, -2.32840792e-15,  8.33944238e-15],
       [ 7.66801842e+01, -5.29522994e-15,  1.24135389e-14],
       [ 1.85649395e+02, -1.28340146e-14,  3.34312837e-14],
       [ 2.00011784e+02, -1.06397789e-14,  3.97554191e-14],
       [ 1.73522028e+02, -9.75351722e-15,  3.12490522e-14],
       [ 3.31214485e+01, -2.21712246e-15,  5.48401477e-15],
       [ 8.71876180e+01,  3.53249956e-16,  1.61445857e-14],
       [ 1.42401139e+02, -8.24540328e-15,  2.38256650e-14],
       [ 1.38496817e+02, -6.80448981e-15,  2.86294037e-14],
       [ 1.77098460e+02, -4.74841387e-15,  3.17927712e-14],
       [ 1.62851785e+02, -5.00961245e-15,  3.08703019e-14],
       [ 3.86223667e+01, -2.53216147e-15